# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: Publish GitHub NuGet package

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build-push:

    runs-on: ubuntu-latest
    permissions:
      packages: write

    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x
    - name: Restore dependencies
      run: dotnet restore -p:EnableWindowsTargeting=true
    - name: Pack
      run: dotnet dotnet pack --no-restore -c Release -o bin/packaged -p:EnableWindowsTargeting=true
    - name: Add GitHub NuGet source
      run: dotnet nuget add source --username Muckenbatscher --password ${{ secrets.GITHUB_TOKEN }} --store-password-in-clear-text --name github "https://nuget.pkg.github.com/Muckenbatscher/index.json"
    - name: Push to GitHub source
      run: dotnet nuget push "bin/packaged/PROJECT_NAME.1.0.0.nupkg" --api-key ${{ secrets.GITHUB_TOKEN }} --source "github"
